### ISSUE TITLE
Gui overlays don't show up when you have the camera's one open.

### ISSUE THREAD

**Issue by Just-MTTC** [BlouFlin/Photography#8]
Gui overlays such as the pumpkin and nether portal ones don't show up if you're in the camera gui, giving you a perfect view

https://github.com/BlouFlin/Photography/assets/173006251/064da4b6-2414-492a-9869-b3e25bd472ea

**Comment by BlouFlin** [comment]
Same as #7. The camera GUI works in the same way as when you hide the in-game HUD with F1, and so hides other overlays. This prevents distractions while you're taking a photo, and also avoids other problems related to photo rendering :)
Otherwise, if you have to find a logical reason in the game universe, maybe it happens because you're looking precisely in the viewfinder, which displays the view from the end of the lens? 🤔
